apiVersion: v1
kind: Service
metadata:
  name: {{ include "port-configurator.fullname" . }}-webhook
spec:
  type: ClusterIP
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: https
  selector:
    {{- include "port-configurator.selectorLabels" . | nindent 4 }}